/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KeanuPortfolioAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "SharedDatabase": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SharedEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "UrlShortenerDynamo": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UrlShortenerFrontend": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}